Repository gazebosim/gz-math, pull requests merged in 2020-08, with the labels that each got.

#140 Sum normalized functions
  include/ignition/math/Vector4.hh
  src/Vector4_TEST.cc
Labels: enhancement, 🏰 citadel, 📜 blueprint, 🔮 dome

#145 Doc Ruby Tests
  README.md
Labels: documentation, tests, 🏰 citadel, 📜 blueprint, 🔮 dome

#139 Update actions CI
  .github/ci/after_make.sh
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  include/ignition/math/Filter.hh
  include/ignition/math/MassMatrix3.hh
  include/ignition/math/SignalStats.hh
  src/Frustum_TEST.cc
  src/Helpers_TEST.cc
  src/RotationSpline_TEST.cc
Labels: tests, 🏰 citadel, 📜 blueprint, 🔮 dome

#133 Add Max and Min function to Vector2.hh
  include/ignition/math/Vector2.hh
  src/Vector2.i
  src/Vector2_TEST.cc
  src/Vector2_TEST.rb
Labels: enhancement, 🏰 citadel, 📜 blueprint, 🔮 dome

#148 👩‍🌾 Fix Vector2 Ruby tests
  src/Vector2.i
  src/Vector2_TEST.rb
Labels: tests, 🏰 citadel, 📜 blueprint, 🔮 dome

#151 Fix IGNITION_MATH_XXX_VERSION
  include/ignition/math/config.hh.in
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome
