Repository gazebosim/gz-math, pull requests merged in 2020-09, with the labels that each got.

#150 Added functions to convert between time_point and secNsec
  include/ignition/math/Helpers.hh
  src/Helpers_TEST.cc
Labels: enhancement, 🏰 citadel, 📜 blueprint, 🔮 dome

#152 Add string to time function
  include/ignition/math/Helpers.hh
  src/Helpers_TEST.cc
Labels: enhancement, 🏰 citadel, 📜 blueprint, 🔮 dome

#155 ⬆️ 6.5.0
  CMakeLists.txt
  Changelog.md
  include/ignition/math/Helpers.hh
  src/Helpers_TEST.cc
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#158 Added secNsecToDuration to helpers functions
  include/ignition/math/Helpers.hh
  src/Helpers_TEST.cc
Labels: beta, 🏰 citadel, 📜 blueprint, 🔮 dome

#159 ⬆️ 6.6.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome

#160 Stable 6.6.0 release
  CMakeLists.txt
Labels: 🏰 citadel, 📜 blueprint, 🔮 dome
