Repository gazebosim/gz-math, pull requests merged in 2020-07, with the labels that each got.

#125 Add setter/getter for Pose's each element - Issue 35
  include/ignition/math/Pose3.hh
  src/Pose_TEST.cc
Labels: enhancement, 🏰 citadel, 📜 blueprint, 🔮 dome

#130 [Issue #71] Update vector2 fuctions from vector3
  include/ignition/math/Vector2.hh
  src/Vector2_TEST.cc
Labels: enhancement

#132 Vector3 to vector4 functions
  include/ignition/math/Vector4.hh
  src/Vector4_TEST.cc
Labels: enhancement, 🏰 citadel, 📜 blueprint, 🔮 dome

#135 Add Abs, Dot and AbsDot and respective tests to Vector4
  include/ignition/math/Vector4.hh
  src/Vector4_TEST.cc
Labels: enhancement, 🏰 citadel, 📜 blueprint, 🔮 dome

#143 Create abs, absDot and Correct functions for Vector2d
  include/ignition/math/Vector2.hh
  src/Vector2_TEST.cc
Labels: enhancement, 🏰 citadel, 📜 blueprint, 🔮 dome

#137 Vector4 Ruby tests - Vector4.i and Vector4_TEST.rb
  src/CMakeLists.txt
  src/Vector4.i
  src/Vector4_TEST.rb
  src/ign_math.i
Labels: tests, 🏰 citadel, 📜 blueprint, 🔮 dome
