Repository gazebosim/gz-math, pull requests merged in 2021-02, with the labels that each got.

#189 Added issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#191 Matrix 4 multiplication test
  src/Matrix4_TEST.cc
Labels: tests

#192 Add instructions to build and run examples
  examples/README.md
Labels: documentation, 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome

#193 Removed issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/port.md
Labels: 🏢 edifice, 🏰 citadel, 📜 blueprint, 🔮 dome
