Repository gazebosim/gz-math, pull requests merged in 2021-08, with the labels that each got.

#217 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress

#223 SWIG Python compilation with CMake >= 3.13
  CMakeLists.txt
  src/CMakeLists.txt
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress

#225 Add Doxygen documentation checks to CI
  .github/workflows/ci.yml
  include/ignition/math/Cylinder.hh
  include/ignition/math/Ellipsoid.hh
  include/ignition/math/SignalStats.hh
  include/ignition/math/SphericalCoordinates.hh
Labels: documentation, 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress

#226 Python interface: Renames methods to match PEP8 style
  examples/angle_example.py
  examples/vector2_example.py
  examples/vector3_example.py
  src/CMakeLists.txt
  src/Rand_TEST.py
  src/python/Angle.i
  src/python/Angle_TEST.py
  src/python/CMakeLists.txt
  src/python/GaussMarkovProcess.i
  src/python/GaussMarkovProcess_TEST.py
  src/python/Rand.i
  src/python/Rand_TEST.py
  src/python/Vector2.i
  src/python/Vector2_TEST.py
  src/python/Vector3.i
  src/python/Vector3_TEST.py
  src/python/Vector4.i
  src/python/Vector4_TEST.py
  src/python/python.i
  src/python/python_TEST.py
  src/ruby/Angle.i
  src/ruby/Angle_TEST.rb
  src/ruby/CMakeLists.txt
  src/ruby/GaussMarkovProcess.i
  src/ruby/GaussMarkovProcess_TEST.rb
  src/ruby/Rand.i
  src/ruby/Rand_TEST.rb
  src/ruby/Vector2.i
  src/ruby/Vector2_TEST.rb
  src/ruby/Vector3.i
  src/ruby/Vector3_TEST.rb
  src/ruby/Vector4.i
  src/ruby/Vector4_TEST.rb
  src/ruby/ruby.i
  src/ruby/ruby_TEST.rb
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress

#227 👩‍🌾 Remove bitbucket-pipelines.yml
  bitbucket-pipelines.yml
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress

#220 Adds Line2, Line3, SignalStats, Temperature python interface
  include/ignition/math/Line2.hh
  src/python/CMakeLists.txt
  src/python/Line2.i
  src/python/Line2_TEST.py
  src/python/Line3.i
  src/python/Line3_TEST.py
  src/python/SignalStats.i
  src/python/SignalStats_TEST.py
  src/python/Temperature.i
  src/python/Temperature_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress

#231 Adds python interface to triangle.
  src/python/CMakeLists.txt
  src/python/Triangle.i
  src/python/Triangle_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️
