Repository gazebosim/gz-math, pull requests merged in 2021-09, with the labels that each got.

#229 Adds python interface to PID and SemanticVersion.
  src/python/CMakeLists.txt
  src/python/PID.i
  src/python/PID_TEST.py
  src/python/SemanticVersion.i
  src/python/SemanticVersion_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#224 Add eigen utils to convert mesh 3d vertices to oriented box
  eigen3/include/ignition/math/eigen3/Util.hh
  eigen3/src/Util_TEST.cc
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress

#232 Adds python interface for Kmeans and Vector3Stats
  src/python/CMakeLists.txt
  src/python/Kmeans.i
  src/python/Kmeans_TEST.py
  src/python/Vector3Stats.i
  src/python/Vector3Stats_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#218 Adds python interface to RollingMean, Color and Spline
  src/python/CMakeLists.txt
  src/python/Color.i
  src/python/Color_TEST.py
  src/python/RollingMean.i
  src/python/RollingMean_TEST.py
  src/python/Spline.i
  src/python/Spline_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress

#236 Add options to install python/ruby in system standard paths
  CMakeLists.txt
  src/python/CMakeLists.txt
  src/ruby/CMakeLists.txt
Labels: 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#222 Add Vector(2|3|4)<T>::NaN to easily create invalid vectors
  include/ignition/math/Vector2.hh
  include/ignition/math/Vector3.hh
  include/ignition/math/Vector4.hh
  src/Vector2_TEST.cc
  src/Vector3_TEST.cc
  src/Vector4_TEST.cc
  src/python/Vector2.i
  src/python/Vector2_TEST.py
  src/python/Vector3.i
  src/python/Vector3_TEST.py
  src/python/Vector4.i
  src/python/Vector4_TEST.py
  src/ruby/Vector2.i
  src/ruby/Vector2_TEST.rb
  src/ruby/Vector3.i
  src/ruby/Vector3_TEST.rb
  src/ruby/Vector4.i
  src/ruby/Vector4_TEST.rb
Labels: 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress

#235 🌐 Spherical coordinates: bug fix, docs and sanity checks
  Migration.md
  include/ignition/math/SphericalCoordinates.hh
  src/SphericalCoordinates.cc
  src/SphericalCoordinates_TEST.cc
Labels: bug, 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#221 Adds python interface to Quaternion, Pose3, Matrix3 and Matrix4
  include/ignition/math/Pose3.hh
  src/Matrix3_TEST.cc
  src/Matrix4_TEST.cc
  src/python/CMakeLists.txt
  src/python/Matrix3.i
  src/python/Matrix3_TEST.py
  src/python/Matrix4.i
  src/python/Matrix4_TEST.py
  src/python/Pose3.i
  src/python/Pose3_TEST.py
  src/python/Quaternion.i
  src/python/Quaternion_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress

#230 Adds python interface to Filter, MovingWindowFilter, RotationSpline.
  src/python/CMakeLists.txt
  src/python/Filter.i
  src/python/Filter_TEST.py
  src/python/MovingWindowFilter.i
  src/python/MovingWindowFilter_TEST.py
  src/python/RotationSpline.i
  src/python/RotationSpline_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#239 Use python executable variable instead of hardcode python3
  CMakeLists.txt
  src/python/CMakeLists.txt
Labels: bug, 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#242 Fix Bazel build.
  eigen3/BUILD.bazel
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#243 More suggestions to #219
  include/ignition/math/Box.hh
  include/ignition/math/Plane.hh
  include/ignition/math/Sphere.hh
  include/ignition/math/detail/Box.hh
  include/ignition/math/detail/Sphere.hh
  src/Box_TEST.cc
  src/Plane_TEST.cc
  src/Sphere_TEST.cc
Labels: beta, 🏯 fortress

#245 🎈 6.9.0~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#252 Add MACOS install instructions
  tutorials/installation.md
Labels: documentation, 🏰 citadel, 🔮 dome, OSX, beta, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#253 Readme Folder Structure
  README.md
Labels: documentation, 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#254 🎈 6.9.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#255 Avoid assertAlmostEqual for python strings
  src/python/Color_TEST.py
  src/python/Pose3_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#256 Prepare for 6.9.1~pre1
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🔮 dome, beta, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#257 Pose3_TEST.py: use 0.01 (not 0) in string test
  CMakeLists.txt
  Changelog.md
  src/python/Pose3_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#258 Prepare for 6.9.1 Release
  CMakeLists.txt
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️
