Repository gazebosim/gz-math, pull requests merged in 2021-12, with the labels that each got.

#289 Defer regex construction to avoid static initialization
  Changelog.md
  src/Helpers.cc
Labels: bug

#290 Defer Material::Predefined construction to avoid static initialization
  Changelog.md
  include/ignition/math/MaterialType.hh
  src/Material.cc
  src/MaterialType.hh
Labels: bug

#298 Document that euler angles should be in radians for quaternion constructor
  include/ignition/math/Quaternion.hh
Labels: documentation, 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#295 Speed up Helpers::Pair test
  src/Helpers_TEST.cc
Labels: tests

#304 Add example and modify document for class Color
  examples/CMakeLists.txt
  examples/color_example.cc
  include/ignition/math/Color.hh
  tutorials.md.in
  tutorials/color.md
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#280 Vector2, 3 and 4 with pybind11
  .github/ci/packages.apt
  CMakeLists.txt
  include/ignition/math/Vector2.hh
  include/ignition/math/Vector3.hh
  include/ignition/math/Vector4.hh
  src/CMakeLists.txt
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Vector2.hh
  src/python_pybind11/src/Vector3.hh
  src/python_pybind11/src/Vector4.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Vector2_TEST.py
  src/python_pybind11/test/Vector3_TEST.py
  src/python_pybind11/test/Vector4_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#320 Fix Color::HSV() incorrect hue output
  Migration.md
  src/Color.cc
  src/Color_TEST.cc
  src/python/Color_TEST.py
  tutorials/color.md
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#311 Added Angle Pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Angle.cc
  src/python_pybind11/src/Angle.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Angle_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#312 Added Rand pybind11 interface and example
  examples/CMakeLists.txt
  examples/rand_example.cc
  examples/rand_example.py
  examples/rand_view_normal.gp
  examples/rand_view_uniform.gp
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Rand.cc
  src/python_pybind11/src/Rand.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Rand_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#313 Add Helpers pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Helpers.cc
  src/python_pybind11/src/Helpers.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Helpers_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#318 Added Color pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Color.cc
  src/python_pybind11/src/Color.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Color_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#316 Add Line2 pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Line2.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Line2_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#322 Added RollingMean pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/RollingMean.cc
  src/python_pybind11/src/RollingMean.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/RollingMean_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#319 Added StopWatch pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/StopWatch.cc
  src/python_pybind11/src/StopWatch.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/StopWatch_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#324 Added Quaternion pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Quaternion.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Quaternion_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#317 Added Line3 pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Line3.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Line3_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#321 Added MovingWindowFilter pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/MovingWindowFilter.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/MovingWindowFilter_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#325 Added Matrix3 pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Matrix3.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Matrix3_TEST.py
  src/python_pybind11/test/Quaternion_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#331 Added SemanticVersion pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/SemanticVersion.cc
  src/python_pybind11/src/SemanticVersion.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/SemanticVersion_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#336 Added Filter pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Filter.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Filter_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#332 Added Spline pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Spline.cc
  src/python_pybind11/src/Spline.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Spline_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#333 Added Triangle pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Triangle.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Triangle_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#334 Added Pose3 pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Pose3.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Pose3_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#335 Added Triangle3 pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Triangle3.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Triangle3_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#341 Added Kmeans pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Kmeans.cc
  src/python_pybind11/src/Kmeans.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Kmeans_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#340 Added Material pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Material.cc
  src/python_pybind11/src/Material.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Material_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#339 Added RotationSpline pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/RotationSpline.cc
  src/python_pybind11/src/RotationSpline.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/RotationSpline_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#315 Add GaussMarkovProcess pybind11 interface and examples
  examples/gauss_markov_process_example.py
  examples/gauss_markov_process_example.rb
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/GaussMarkovProcess.cc
  src/python_pybind11/src/GaussMarkovProcess.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/GaussMarkovProcess_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#338 Added AxisAlignedBox pybind11 interface
  include/ignition/math/AxisAlignedBox.hh
  src/AxisAlignedBox.cc
  src/AxisAlignedBox_TEST.cc
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/AxisAlignedBox.cc
  src/python_pybind11/src/AxisAlignedBox.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/AxisAlignedBox_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️

#345 Added MassMatrix3 pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/MassMatrix3.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/MassMatrix3_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#314 Add DiffDriveOdometry pybind11 interface and examples
  examples/CMakeLists.txt
  examples/angle_example.py
  examples/diff_drive_odometry.cc
  examples/diff_drive_odometry.py
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/DiffDriveOdometry.cc
  src/python_pybind11/src/DiffDriveOdometry.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/DiffDriveOdometry_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#330 Added Temperature pybind11 interface
  include/ignition/math/Temperature.hh
  src/Temperature.cc
  src/Temperature_TEST.cc
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Temperature.cc
  src/python_pybind11/src/Temperature.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Temperature_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#323 Added PID pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/PID.cc
  src/python_pybind11/src/PID.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/PID_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#337 Added Matrix4 pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Matrix4.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Matrix4_TEST.py
  src/python_pybind11/test/Quaternion_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#347 Added Box pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Box.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Box_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️

#349 Added Inertial pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Inertial.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Inertial_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#350 Added OrientedBox pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/OrientedBox.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/OrientedBox_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#348 Added Cylinder pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Cylinder.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Cylinder_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#346 Added Plane pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Box.hh
  src/python_pybind11/src/Plane.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Box_TEST.py
  src/python_pybind11/test/Plane_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#353 Added Frustum pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Frustum.cc
  src/python_pybind11/src/Frustum.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Frustum_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️

#352 Added Sphere pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Sphere.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Sphere_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️

#343 Added SignalStats pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/SignalStats.cc
  src/python_pybind11/src/SignalStats.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/SignalStats_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#355 Small fixed in doxygen
  include/ignition/math/PID.hh
  include/ignition/math/Quaternion.hh
  include/ignition/math/Spline.hh
Labels: documentation, 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#356 kmeans examples in cpp and python
  examples/CMakeLists.txt
  examples/kmeans.cc
  examples/kmeans.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#351 Added Vector3Stats pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Vector3Stats.cc
  src/python_pybind11/src/Vector3Stats.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Vector3Stats_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️

#357 Added SphericalCoordinates pybind11 interface
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/SphericalCoordinates.cc
  src/python_pybind11/src/SphericalCoordinates.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/SphericalCoordinates_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#358 6.9.2 ➡️ 7 (main)
  Changelog.md
  include/ignition/math/Cylinder.hh
  include/ignition/math/Triangle3.hh
  src/Helpers_TEST.cc
  src/Inertial_TEST.cc
  src/python/CMakeLists.txt
  src/python/Color_TEST.py
  src/python/Helpers.i
  src/python/Helpers_TEST.py
  src/python/Material.i
  src/python/MaterialType.i
  src/python/Material_TEST.py
  src/python/Pose3_TEST.py
  src/python/StopWatch.i
  src/python/StopWatch_TEST.py
  src/python/Triangle3.i
  src/python/Triangle3_TEST.py
  src/python/python.i
Labels: 🌱 garden

#354 Move SWIG interfaces from python to ruby
  src/CMakeLists.txt
  src/python/Angle.i
  src/python/CMakeLists.txt
  src/python/GaussMarkovProcess.i
  src/python/Rand.i
  src/python/Vector2.i
  src/python/Vector3.i
  src/python/Vector4.i
  src/python/python.i
  src/python/python_TEST.py
  src/ruby/AxisAlignedBox.i
  src/ruby/Box.i
  src/ruby/Color.i
  src/ruby/Cylinder.i
  src/ruby/DiffDriveOdometry.i
  src/ruby/Filter.i
  src/ruby/Frustum.i
  src/ruby/Helpers.i
  src/ruby/Inertial.i
  src/ruby/Kmeans.i
  src/ruby/Line2.i
  src/ruby/Line3.i
  src/ruby/MassMatrix3.i
  src/ruby/Material.i
  src/ruby/MaterialType.i
  src/ruby/Matrix3.i
  src/ruby/Matrix4.i
  src/ruby/MovingWindowFilter.i
  src/ruby/OrientedBox.i
  src/ruby/PID.i
  src/ruby/Plane.i
  src/ruby/Pose3.i
  src/ruby/Quaternion.i
  src/ruby/RollingMean.i
  src/ruby/RotationSpline.i
  src/ruby/SemanticVersion.i
  src/ruby/SignalStats.i
  src/ruby/Sphere.i
  src/ruby/SphericalCoordinates.i
  src/ruby/Spline.i
  src/ruby/StopWatch.i
  src/ruby/Temperature.i
  src/ruby/Triangle.i
  src/ruby/Triangle3.i
  src/ruby/Vector3Stats.i
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️
