Repository gazebosim/gz-math, pull requests merged in 2021-11, with the labels that each got.

#265 DiffDriveOdometry Python interface
  src/python/CMakeLists.txt
  src/python/DiffDriveOdometry.i
  src/python/DiffDriveOdometry_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#273 Box Python interfaces
  src/python/Box.i
  src/python/Box_TEST.py
  src/python/CMakeLists.txt
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#275 Inertial Python interface
  src/python/CMakeLists.txt
  src/python/Inertial.i
  src/python/Inertial_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#249 [backport ign-math6] Added examples to tutorials.md.in
  examples/angle_example.cc
  examples/angle_example.rb
  examples/quaternion_from_euler.cc
  examples/quaternion_to_euler.cc
  examples/triangle_example.cc
  examples/vector2_example.cc
  tutorials.md.in
  tutorials/angle.md
  tutorials/rotation.md
  tutorials/triangle.md
  tutorials/vector.md
Labels: documentation, 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#279 Internal URL fixed (paragraph 266)
  tutorials/installation.md
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#276 OrientedBox Python interface
  src/python/CMakeLists.txt
  src/python/OrientedBox.i
  src/python/OrientedBox_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#281 AxisAlignedBox: rename some python methods
  src/python/AxisAlignedBox.i
  src/python/AxisAlignedBox_TEST.py
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#282 quaternion_from_euler example: input degrees
  examples/quaternion_from_euler.cc
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#278 Frustrum Python interface
  src/python/CMakeLists.txt
  src/python/Frustum.i
  src/python/Frustum_TEST.py
  src/python/python.i
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️, 🌱 garden

#285 Modified cmake target name for Ruby interfaces
  src/ruby/CMakeLists.txt
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden

#284 Fix windows warnings in Vector2, 3 and 4
  include/ignition/math/Vector2.hh
  include/ignition/math/Vector3.hh
  include/ignition/math/Vector4.hh
Labels: 🏰 citadel, 🔮 dome, 🏢 edifice, 🏯 fortress, Gazebo 1️1️, 🌱 garden
