Repository gazebosim/gz-math, pull requests merged in 2022-06, with the labels that each got.

#432 Subtraction operator for Inertial class
  include/gz/math/Inertial.hh
  src/Inertial_TEST.cc
  src/python_pybind11/src/Inertial.hh
  src/python_pybind11/test/Inertial_TEST.py
  src/ruby/Inertial.i
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#438 Pose3: deprecate - and -= operators
  Migration.md
  include/gz/math/Pose3.hh
  src/Pose_TEST.cc
Labels: 🌱 garden

#440 Add Aditya as codeowner
  .github/CODEOWNERS
Labels: 🌱 garden

#441 [ign -> gz] CMake functions
  CMakeLists.txt
  eigen3/include/gz/math/CMakeLists.txt
  eigen3/src/CMakeLists.txt
  include/gz/math/CMakeLists.txt
  src/CMakeLists.txt
  src/graph/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#443 Add Aditya as codeowner (backport to ign-math6 branch)
  .github/CODEOWNERS
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#444 Suppress warnings
  src/python_pybind11/src/Filter.hh
  src/python_pybind11/src/SignalStats.cc
  src/ruby/CMakeLists.txt
  test/integration/deprecated_TEST.cc
Labels: 🌱 garden

#420 Rename CMake project to gz
  BUILD.bazel
  CMakeLists.txt
  eigen3/BUILD.bazel
  examples/CMakeLists.txt
  src/CMakeLists.txt
  src/ruby/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#445 ign -> gz Partial Docs Migration and Project Name Followups : gz-math
  Changelog.md
  Migration.md
  README.md
  api.md.in
  configure.bat
  examples/CMakeLists.txt
  examples/README.md
  src/Helpers_TEST.cc
  src/Quaternion_TEST.cc
  tutorials.md.in
  tutorials/angle.md
  tutorials/color.md
  tutorials/example_angle.md
  tutorials/example_triangle.md
  tutorials/example_vector2.md
  tutorials/installation.md
  tutorials/rotation.md
  tutorials/rotation_example.md
  tutorials/triangle.md
  tutorials/vector.md
Labels: 🌱 garden

#446 Use pytest to generate junit xml files for python tests
  .github/ci/packages.apt
  src/python_pybind11/CMakeLists.txt
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️
