Repository gazebosim/gz-math, pull requests merged in 2022-05, with the labels that each got.

#415 Backport #414: packages.apt install libpython3-dev
  .github/ci/packages.apt
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#412 Add linear interpolation methods.
  include/ignition/math/VolumetricGridLookupField.hh
  include/ignition/math/detail/AxisIndex.hh
  include/ignition/math/detail/InterpolationPoint.hh
  src/InterpolationPoint_TEST.cc
  src/VolumetricGridLookupField_TEST.cc
Labels: 🌱 garden, MBARI-LRAUV

#411 Remove CI files that aren't used anymore
  appveyor.yml
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#417 README: update jenkins job badges
  README.md
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#418 README: update jenkins job badges
  README.md
Labels: 🌱 garden

#421 Merge ign-math6 -> main
  appveyor.yml
Labels: 🌱 garden

#422 Fix return policies for some member functions
  include/ignition/math/Pose3.hh
  src/python_pybind11/src/AxisAlignedBox.cc
  src/python_pybind11/src/Cylinder.hh
  src/python_pybind11/src/Inertial.hh
  src/python_pybind11/src/Matrix3.hh
  src/python_pybind11/src/Matrix4.hh
  src/python_pybind11/src/OrientedBox.hh
  src/python_pybind11/src/Plane.hh
  src/python_pybind11/src/Pose3.hh
  src/python_pybind11/src/RotationSpline.cc
  src/python_pybind11/src/Vector3Stats.cc
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#426 6 ➡️ main
  include/gz/math/Pose3.hh
  src/python_pybind11/src/AxisAlignedBox.cc
  src/python_pybind11/src/Cylinder.hh
  src/python_pybind11/src/Inertial.hh
  src/python_pybind11/src/Matrix3.hh
  src/python_pybind11/src/Matrix4.hh
  src/python_pybind11/src/OrientedBox.hh
  src/python_pybind11/src/Plane.hh
  src/python_pybind11/src/Pose3.hh
  src/python_pybind11/src/RotationSpline.cc
  src/python_pybind11/src/Vector3Stats.cc
Labels: 🌱 garden

#424 MassMatrix3: fix bug in PrincipalAxesOffset tolerances
  include/ignition/math/MassMatrix3.hh
  src/MassMatrix3_TEST.cc
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#428 Prepare 6.11.0 release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️
