Repository gazebosim/gz-math, pull requests merged in 2022-09, with the labels that each got.

#491 Merge ign-math6 ➡️ gz-math7
  Changelog.md
  eigen3/include/ignition/math/eigen3/Conversions.hh
  eigen3/include/ignition/math/eigen3/Util.hh
  include/ignition/math/AxisAlignedBox.hh
  include/ignition/math/Box.hh
  include/ignition/math/Capsule.hh
  include/ignition/math/Color.hh
  include/ignition/math/Cylinder.hh
  include/ignition/math/DiffDriveOdometry.hh
  include/ignition/math/Ellipsoid.hh
  include/ignition/math/Filter.hh
  include/ignition/math/Frustum.hh
  include/ignition/math/GaussMarkovProcess.hh
  include/ignition/math/Inertial.hh
  include/ignition/math/Kmeans.hh
  include/ignition/math/Line2.hh
  include/ignition/math/Line3.hh
  include/ignition/math/MassMatrix3.hh
  include/ignition/math/Material.hh
  include/ignition/math/MaterialType.hh
  include/ignition/math/Matrix3.hh
  include/ignition/math/Matrix4.hh
  include/ignition/math/MovingWindowFilter.hh
  include/ignition/math/OrientedBox.hh
  include/ignition/math/PID.hh
  include/ignition/math/Plane.hh
  include/ignition/math/Pose3.hh
  include/ignition/math/Quaternion.hh
  include/ignition/math/Rand.hh
  include/ignition/math/RollingMean.hh
  include/ignition/math/RotationSpline.hh
  include/ignition/math/SemanticVersion.hh
  include/ignition/math/SignalStats.hh
  include/ignition/math/SpeedLimiter.hh
  include/ignition/math/Sphere.hh
  include/ignition/math/SphericalCoordinates.hh
  include/ignition/math/Spline.hh
  include/ignition/math/Stopwatch.hh
  include/ignition/math/Temperature.hh
  include/ignition/math/Triangle.hh
  include/ignition/math/Triangle3.hh
  include/ignition/math/Vector2.hh
  include/ignition/math/Vector3.hh
  include/ignition/math/Vector3Stats.hh
  include/ignition/math/Vector4.hh
  include/ignition/math/graph/Edge.hh
  include/ignition/math/graph/Graph.hh
  include/ignition/math/graph/GraphAlgorithms.hh
  include/ignition/math/graph/Vertex.hh
Labels: 🌱 garden

#492 🌱🥳: Fixes to tutorials
  README.md
  tutorials/angle.md
  tutorials/example_angle.md
  tutorials/example_triangle.md
  tutorials/example_vector2.md
  tutorials/rotation.md
  tutorials/rotation_example.md
  tutorials/vector.md
Labels: documentation, 🌱 garden

#496 Fixed color example
  tutorials/color.md
Labels: 🌱 garden

#493 Improved installation tutorial
  tutorials/installation.md
Labels: 🌱 garden

#495 Fixed triangule tutorial instructions
  tutorials/triangle.md
Labels: 🌱 garden

#497 Add pybind11 module as MODULE
  src/python_pybind11/CMakeLists.txt
Labels: bug, 🌱 garden

#494 Fixed quaternion from euler example
  examples/quaternion_from_euler.cc
Labels: 🌱 garden

#499 Migration guide: remove outdated entry
  Migration.md
Labels: 🌱 garden

#501 Getting started tutorial: add compiler command
  tutorials/cppgetstarted.md
Labels: 🌱 garden, tutorial-party

#502 Python tutorial: show expected output
  tutorials/pythongetstarted.md
Labels: 🌱 garden, tutorial-party

#504 Prepare 7.0.0~pre2 version
  CMakeLists.txt
Labels: 🌱 garden

#500 tutorial update: macOS binary install
  tutorials/installation.md
Labels: 🌱 garden, tutorial-party

#505 Fixed cppgetstarted visualization
  tutorials/cppgetstarted.md
Labels: 🌱 garden

#506 Update Changelog for 7.0.0
  Changelog.md
Labels: 🌱 garden

#509 7.0.0 release
  CMakeLists.txt
Labels: 🌱 garden

#510 Disable tests failing on arm64
  src/Helpers_TEST.cc
  src/Pose_TEST.cc
Labels: 🌱 garden

#511 7.0.1 release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#512 Fix arm test
  src/Helpers_TEST.cc
  src/Pose_TEST.cc
Labels: 🌱 garden
