Repository gazebosim/gz-math, pull requests merged in 2022-08, with the labels that each got.

#456 Adds a Time Interpolation API
  include/gz/math/TimeVaryingVolumetricGrid.hh
  include/gz/math/TimeVaryingVolumetricGridLookupField.hh
  include/gz/math/detail/InterpolationPoint.hh
  src/TimeVaryingVolumetricGridLookupField_TEST.cc
  src/TimeVaryingVolumetricGrid_TEST.cc
Labels: enhancement, 🌱 garden, MBARI-LRAUV

#478 ⬆️ Bump main to 8.0.0~pre1
  BUILD.bazel
  CMakeLists.txt
  Changelog.md
  README.md
  examples/CMakeLists.txt
  tutorials/color.md
Labels: 🌱 garden

#480 Add option to skip pybind11 and SWIG
  CMakeLists.txt
  src/CMakeLists.txt
Labels: bug, 🌱 garden

#479 ign -> gz : Remove redundant namespace references
  src/AxisAlignedBox.cc
  src/AxisAlignedBox_TEST.cc
  src/Frustum_TEST.cc
  src/Inertial_TEST.cc
  src/MovingWindowFilter_TEST.cc
  src/OrientedBox_TEST.cc
  src/PID.cc
  src/RotationSpline.cc
  src/SpeedLimiter.cc
  src/Sphere_TEST.cc
  src/SphericalCoordinates.cc
  src/SphericalCoordinates_TEST.cc
  src/Stopwatch_TEST.cc
  src/Temperature.cc
Labels: 🏰 citadel, 🏯 fortress, ign to gz

#481 Merge ign-math6 ➡️ gz-math7
  Changelog.md
  src/AxisAlignedBox.cc
  src/AxisAlignedBox_TEST.cc
  src/Frustum_TEST.cc
  src/Inertial_TEST.cc
  src/MovingWindowFilter_TEST.cc
  src/OrientedBox_TEST.cc
  src/PID.cc
  src/RotationSpline.cc
  src/SpeedLimiter.cc
  src/Sphere_TEST.cc
  src/SphericalCoordinates.cc
  src/SphericalCoordinates_TEST.cc
  src/Stopwatch_TEST.cc
  src/Temperature.cc
Labels: bug, 🌱 garden

#488 Fixed Windows build in gz-math7
  src/python_pybind11/CMakeLists.txt
Labels: 🌱 garden

#490 ⬆️ Bump 6.12.0 to 6.13.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏯 fortress
