Repository gazebosim/gz-math, pull requests merged in 2022-07, with the labels that each got.

#434 Compute distance between points on a general celestial body
  Migration.md
  include/gz/math/SphericalCoordinates.hh
  src/SphericalCoordinates.cc
  src/SphericalCoordinates_TEST.cc
  src/python_pybind11/src/SphericalCoordinates.cc
  src/python_pybind11/test/SphericalCoordinates_TEST.py
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#452 SphericalCoordinates: make query methods const
  include/gz/math/SphericalCoordinates.hh
  src/SphericalCoordinates.cc
Labels: 🌱 garden

#454 Remove deprecated appendToStream - they're new on v7
  include/gz/math/Helpers.hh
  src/Helpers_TEST.cc
Labels: 🌱 garden, MBARI buoy

#455 Add Matrix6 class
  eigen3/include/ignition/math/eigen3/Conversions.hh
  eigen3/src/Conversions_TEST.cc
  include/ignition/math/Matrix6.hh
  src/Matrix6_TEST.cc
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Matrix6.cc
  src/python_pybind11/src/Matrix6.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Matrix6_TEST.py
Labels: 🏰 citadel, 🏯 fortress, scripting, MBARI buoy

#458 Merge ign-math6 ➡️ main
  .github/ci/packages.apt
  Changelog.md
  eigen3/include/gz/math/eigen3/Conversions.hh
  eigen3/src/Conversions_TEST.cc
  include/gz/math/MassMatrix3.hh
  include/gz/math/Matrix6.hh
  include/ignition/math/Matrix6.hh
  src/MassMatrix3_TEST.cc
  src/Matrix6_TEST.cc
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Interval.cc
  src/python_pybind11/src/Interval.hh
  src/python_pybind11/src/Matrix6.cc
  src/python_pybind11/src/Matrix6.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Interval_TEST.py
  src/python_pybind11/test/Matrix6_TEST.py
Labels: 🌱 garden, MBARI buoy

#457 Alphabetize examples
  examples/CMakeLists.txt
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#451 Added Polynomial3 Python interface
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Polynomial3.cc
  src/python_pybind11/src/Polynomial3.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Polynomial3_TEST.py
Labels: 🏰 citadel, 🏯 fortress, scripting

#466 ign -> gz Tick-tock Python Libs : gz-math
  src/python_pybind11/CMakeLists.txt
Labels: scripting, 🌱 garden, ign to gz

#463 ign -> gz Provisional Finale: Source Migration : gz-math
  include/gz/math/math.hh.in
  src/python_pybind11/src/Angle.hh
  src/python_pybind11/src/AxisAlignedBox.hh
  src/python_pybind11/src/Box.hh
  src/python_pybind11/src/Capsule.hh
  src/python_pybind11/src/Color.hh
  src/python_pybind11/src/Cylinder.hh
  src/python_pybind11/src/DiffDriveOdometry.hh
  src/python_pybind11/src/Ellipsoid.hh
  src/python_pybind11/src/Filter.hh
  src/python_pybind11/src/Frustum.hh
  src/python_pybind11/src/GaussMarkovProcess.hh
  src/python_pybind11/src/Helpers.hh
  src/python_pybind11/src/Inertial.hh
  src/python_pybind11/src/Interval.hh
  src/python_pybind11/src/Kmeans.hh
  src/python_pybind11/src/Line2.hh
  src/python_pybind11/src/Line3.hh
  src/python_pybind11/src/MassMatrix3.hh
  src/python_pybind11/src/Material.hh
  src/python_pybind11/src/Matrix3.hh
  src/python_pybind11/src/Matrix4.hh
  src/python_pybind11/src/MovingWindowFilter.hh
  src/python_pybind11/src/OrientedBox.hh
  src/python_pybind11/src/PID.hh
  src/python_pybind11/src/Plane.hh
  src/python_pybind11/src/Pose3.hh
  src/python_pybind11/src/Quaternion.hh
  src/python_pybind11/src/Rand.hh
  src/python_pybind11/src/RollingMean.hh
  src/python_pybind11/src/RotationSpline.hh
  src/python_pybind11/src/SemanticVersion.hh
  src/python_pybind11/src/SignalStats.hh
  src/python_pybind11/src/Sphere.hh
  src/python_pybind11/src/SphericalCoordinates.hh
  src/python_pybind11/src/Spline.hh
  src/python_pybind11/src/StopWatch.hh
  src/python_pybind11/src/Temperature.hh
  src/python_pybind11/src/Triangle.hh
  src/python_pybind11/src/Triangle3.hh
  src/python_pybind11/src/Vector2.hh
  src/python_pybind11/src/Vector3.hh
  src/python_pybind11/src/Vector3Stats.hh
  src/python_pybind11/src/Vector4.hh
Labels: 🌱 garden, ign to gz

#467 Ignition -> Gazebo
  README.md
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️, QA

#469 Add addition operator to Matrix6
  include/ignition/math/Matrix6.hh
  src/Matrix6_TEST.cc
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Matrix6.hh
  src/python_pybind11/test/Matrix6_TEST.py
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️, MBARI buoy

#471 Added Helper function isTimeString to Python
  src/python_pybind11/src/Helpers.cc
  src/python_pybind11/test/Helpers_TEST.py
Labels: 🏰 citadel, 🏯 fortress, scripting, Gazebo 1️1️

#473 Merge ign-math6 ➡️ main
  .gitignore
  README.md
  include/gz/math/Matrix6.hh
  src/Matrix6_TEST.cc
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Helpers.cc
  src/python_pybind11/src/Matrix6.hh
  src/python_pybind11/src/Polynomial3.cc
  src/python_pybind11/src/Polynomial3.hh
  src/python_pybind11/src/Region3.cc
  src/python_pybind11/src/Region3.hh
  src/python_pybind11/src/_gz_math_pybind11.cc
  src/python_pybind11/test/Helpers_TEST.py
  src/python_pybind11/test/Matrix6_TEST.py
  src/python_pybind11/test/Polynomial3_TEST.py
  src/python_pybind11/test/Region3_TEST.py
Labels: 🌱 garden

#468 Change IGN_DESIGNATION to GZ_DESIGNATION
  api.md.in
  include/ignition/math/CMakeLists.txt
  include/ignition/math/config.hh.in
  test/integration/all_symbols_have_version.bash.in
  tutorials.md.in
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️, ign to gz

#474 Require gz-cmake 2.13
  CMakeLists.txt
Labels: bug, 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#294 Drop unnecessary moving window filter pimpl
  include/gz/math/MovingWindowFilter.hh
  src/MovingWindowFilter.cc
  src/MovingWindowFilter_TEST.cc
Labels: bug, 🌱 garden, Breaking change

#476 🎈 6.12.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏯 fortress, Gazebo 1️1️

#475 VolumetricGridLookupField: generalize index type, add constructor
  include/gz/math/VolumetricGridLookupField.hh
  src/VolumetricGridLookupField_TEST.cc
Labels: enhancement, 🌱 garden

#459 Add fluid added mass to inertial
  include/gz/math/Inertial.hh
  src/Inertial_TEST.cc
Labels: enhancement, 🌱 garden, MBARI buoy, Breaking change
