Repository gazebosim/gz-math, pull requests merged in 2022-04, with the labels that each got.

#398 Add PiecewiseScalarField3 class
  examples/CMakeLists.txt
  examples/piecewise_scalar_field3_example.cc
  include/ignition/math/PiecewiseScalarField3.hh
  src/PiecewiseScalarField3_TEST.cc
Labels: 🌱 garden, MBARI-LRAUV

#403 Added Capsule Python interface
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Capsule.cc
  src/python_pybind11/src/Capsule.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Capsule_TEST.py
Labels: 🏰 citadel, 🏯 fortress, scripting, Gazebo 1️1️, mujoco

#404 Added Ellipsoid Python interface
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Ellipsoid.cc
  src/python_pybind11/src/Ellipsoid.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Ellipsoid_TEST.py
Labels: 🏰 citadel, 🏯 fortress, scripting, Gazebo 1️1️, mujoco

#405 6 to main
  include/ignition/math/Helpers.hh
  src/Helpers_TEST.cc
  src/OrientedBox_TEST.cc
  src/SphericalCoordinates_TEST.cc
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Capsule.cc
  src/python_pybind11/src/Capsule.hh
  src/python_pybind11/src/Ellipsoid.cc
  src/python_pybind11/src/Ellipsoid.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Capsule_TEST.py
  src/python_pybind11/test/Ellipsoid_TEST.py
Labels: 🌱 garden

#408 examples/CMakeLists.txt: fix find version variable
  examples/CMakeLists.txt
Labels: 🌱 garden

#409 Bumps in garden : ign-math7
  .github/ci/packages.apt
  CMakeLists.txt
  README.md
  tutorials/color.md
Labels: 🌱 garden

#410 Bumps in garden : ign-math7
  .github/ci/packages.apt
  CMakeLists.txt
  appveyor.yml
  configure.bat
Labels: 🌱 garden

#400 Fix pybind11 compilation on focal/clang12 combination
  src/python_pybind11/CMakeLists.txt
Labels: 🌱 garden

#414 packages.apt: install libpython3-dev
  .github/ci/packages.apt
Labels: 🌱 garden
