Repository gazebosim/gz-math, pull requests merged in 2022-01, with the labels that each got.

#362 Added Python Getting started tutorial
  tutorials.md.in
  tutorials/pythongetstarted.md
Labels: documentation, 🏰 citadel, 🏢 edifice, 🏯 fortress, scripting, Gazebo 1️1️

#364 Fix Focal on Jenkins
  .github/ci/packages.apt
  examples/CMakeLists.txt
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#365 Cherry-pick "Fix Focal on Jenkins" (#364) onto main
  .github/ci/packages.apt
  examples/CMakeLists.txt
Labels: 🌱 garden

#299 Use ImplPtr from ign-utils where relevant
  .github/ci/packages.apt
  CMakeLists.txt
  include/ignition/math/AxisAlignedBox.hh
  include/ignition/math/Box.hh
  include/ignition/math/Cylinder.hh
  include/ignition/math/DiffDriveOdometry.hh
  include/ignition/math/Frustum.hh
  include/ignition/math/GaussMarkovProcess.hh
  include/ignition/math/Kmeans.hh
  include/ignition/math/Material.hh
  include/ignition/math/PID.hh
  include/ignition/math/RollingMean.hh
  include/ignition/math/RotationSpline.hh
  include/ignition/math/SemanticVersion.hh
  include/ignition/math/Sphere.hh
  include/ignition/math/SphericalCoordinates.hh
  include/ignition/math/Spline.hh
  include/ignition/math/Stopwatch.hh
  include/ignition/math/Temperature.hh
  include/ignition/math/Vector3Stats.hh
  src/AxisAlignedBox.cc
  src/Box_TEST.cc
  src/CMakeLists.txt
  src/DiffDriveOdometry.cc
  src/DiffDriveOdometry_TEST.cc
  src/Frustum.cc
  src/FrustumPrivate.hh
  src/GaussMarkovProcess.cc
  src/Kmeans.cc
  src/KmeansPrivate.hh
  src/Material.cc
  src/Material_TEST.cc
  src/PID.cc
  src/RollingMean.cc
  src/RotationSpline.cc
  src/RotationSplinePrivate.cc
  src/RotationSplinePrivate.hh
  src/SemanticVersion.cc
  src/SphericalCoordinates.cc
  src/Spline.cc
  src/SplinePrivate.cc
  src/SplinePrivate.hh
  src/Stopwatch.cc
  src/Temperature.cc
  src/Vector3Stats.cc
  src/Vector3StatsPrivate.hh
Labels: 🌱 garden

#366 Use const instead of constexpr in Ellipsoid constructor
  include/ignition/math/detail/Ellipsoid.hh
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#367 🎈 6.9.3~pre2
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#363 Merge ign-math6 as of Frustum SWIG to main
  examples/quaternion_from_euler.cc
  include/ignition/math/AxisAlignedBox.hh
  src/python/AxisAlignedBox.i
  src/python/AxisAlignedBox_TEST.py
  src/python/Box.i
  src/python/Box_TEST.py
  src/python/CMakeLists.txt
  src/python/Cylinder.i
  src/python/Cylinder_TEST.py
  src/python/DiffDriveOdometry.i
  src/python/DiffDriveOdometry_TEST.py
  src/python/Frustum.i
  src/python/Frustum_TEST.py
  src/python/Inertial.i
  src/python/Inertial_TEST.py
  src/python/MassMatrix3.i
  src/python/MassMatrix3_TEST.py
  src/python/OrientedBox.i
  src/python/OrientedBox_TEST.py
  src/python/Plane.i
  src/python/Plane_TEST.py
  src/python/Sphere.i
  src/python/Sphere_TEST.py
  src/python/SphericalCoordinates.i
  src/python/SphericalCoordinates_TEST.py
  src/python/python.i
  tutorials/angle.md
  tutorials/installation.md
  tutorials/rotation.md
  tutorials/triangle.md
  tutorials/vector.md
Labels: 🌱 garden

#368 6 ➡️ 7 (main) - as of StopWatch pybind11
  Migration.md
  examples/CMakeLists.txt
  examples/color_example.cc
  examples/rand_example.cc
  examples/rand_example.py
  examples/rand_view_normal.gp
  examples/rand_view_uniform.gp
  include/ignition/math/Color.hh
  include/ignition/math/Vector2.hh
  include/ignition/math/Vector3.hh
  include/ignition/math/Vector4.hh
  src/Color.cc
  src/Color_TEST.cc
  src/python/CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Angle.cc
  src/python_pybind11/src/Angle.hh
  src/python_pybind11/src/Color.cc
  src/python_pybind11/src/Color.hh
  src/python_pybind11/src/Helpers.cc
  src/python_pybind11/src/Helpers.hh
  src/python_pybind11/src/Line2.hh
  src/python_pybind11/src/Rand.cc
  src/python_pybind11/src/Rand.hh
  src/python_pybind11/src/RollingMean.cc
  src/python_pybind11/src/RollingMean.hh
  src/python_pybind11/src/StopWatch.cc
  src/python_pybind11/src/StopWatch.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
  src/python_pybind11/test/Angle_TEST.py
  src/python_pybind11/test/Color_TEST.py
  src/python_pybind11/test/Helpers_TEST.py
  src/python_pybind11/test/Line2_TEST.py
  src/python_pybind11/test/Rand_TEST.py
  src/python_pybind11/test/RollingMean_TEST.py
  src/python_pybind11/test/StopWatch_TEST.py
  tutorials.md.in
  tutorials/color.md
Labels: 🌱 garden

#283 Use constexpr for simple static constants
  Changelog.md
  include/ignition/math/Angle.hh
  include/ignition/math/Color.hh
  include/ignition/math/Matrix3.hh
  include/ignition/math/Matrix4.hh
  include/ignition/math/Pose3.hh
  include/ignition/math/Quaternion.hh
  include/ignition/math/Vector2.hh
  include/ignition/math/Vector3.hh
  include/ignition/math/Vector4.hh
  src/Angle.cc
  src/Color.cc
  src/python_pybind11/src/Vector2.hh
  src/python_pybind11/src/Vector3.hh
  src/python_pybind11/src/Vector4.hh
  src/ruby/Vector2.i
  src/ruby/Vector3.i
  src/ruby/Vector4.i
Labels: 🌱 garden

#361 Fix pybind11 issues with macOS
  include/ignition/math/Quaternion.hh
  src/python_pybind11/test/PID_TEST.py
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#369 🎈 6.10.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️
