Repository gazebosim/gz-math, pull requests merged in 2022-03, with the labels that each got.

#384 Fixed Jammy CI
  CMakeLists.txt
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#382 Reduce pybind11 compilation memory part 3
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/MassMatrix3.cc
  src/python_pybind11/src/MassMatrix3.hh
  src/python_pybind11/src/Matrix3.cc
  src/python_pybind11/src/Matrix3.hh
  src/python_pybind11/src/Matrix4.cc
  src/python_pybind11/src/Matrix4.hh
  src/python_pybind11/src/Pose3.cc
  src/python_pybind11/src/Pose3.hh
  src/python_pybind11/src/Quaternion.cc
  src/python_pybind11/src/Quaternion.hh
  src/python_pybind11/src/Triangle.cc
  src/python_pybind11/src/Triangle.hh
  src/python_pybind11/src/Triangle3.cc
  src/python_pybind11/src/Triangle3.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#385 Merge 6 -> main
  CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Angle.cc
  src/python_pybind11/src/Color.cc
  src/python_pybind11/src/MassMatrix3.cc
  src/python_pybind11/src/MassMatrix3.hh
  src/python_pybind11/src/Matrix3.cc
  src/python_pybind11/src/Matrix3.hh
  src/python_pybind11/src/Matrix4.cc
  src/python_pybind11/src/Matrix4.hh
  src/python_pybind11/src/OrientedBox.hh
  src/python_pybind11/src/Pose3.cc
  src/python_pybind11/src/Pose3.hh
  src/python_pybind11/src/Quaternion.cc
  src/python_pybind11/src/Quaternion.hh
  src/python_pybind11/src/Triangle.cc
  src/python_pybind11/src/Triangle.hh
  src/python_pybind11/src/Triangle3.cc
  src/python_pybind11/src/Triangle3.hh
  src/python_pybind11/src/_ignition_math_pybind11.cc
Labels: 🌱 garden

#386 Remove Bionic from future releases (Garden+)
  .github/workflows/ci.yml
  README.md
  tutorials/installation.md
Labels: documentation, tests, 🌱 garden

#388 Add Interval class
  examples/CMakeLists.txt
  examples/interval_example.cc
  include/ignition/math/Interval.hh
  src/Interval_TEST.cc
Labels: 🌱 garden, MBARI-LRAUV

#390 Add Region3 class
  examples/CMakeLists.txt
  examples/region3_example.cc
  include/ignition/math/Region3.hh
  src/Region3_TEST.cc
Labels: 🌱 garden, MBARI-LRAUV

#393 Add Polynomial3 class
  examples/CMakeLists.txt
  examples/polynomial3_example.cc
  include/ignition/math/Polynomial3.hh
  src/Polynomial3_TEST.cc
Labels: 🌱 garden, MBARI-LRAUV

#389 Added helper function to check if a string represents a time
  include/ignition/math/Helpers.hh
  src/Helpers_TEST.cc
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#374 Fixes for tests on i386: relax SphericalCoordinates and workaround for negative zero
  src/OrientedBox_TEST.cc
  src/SphericalCoordinates_TEST.cc
Labels: 🏰 citadel, 🏢 edifice, 🏯 fortress, Gazebo 1️1️

#397 Add AdditivelySeparableScalarField3 class
  examples/CMakeLists.txt
  examples/additively_separable_scalar_field3_example.cc
  include/ignition/math/AdditivelySeparableScalarField3.hh
  src/AdditivelySeparableScalarField3_TEST.cc
Labels: 🌱 garden, MBARI-LRAUV

#396 Fix unsafe globals in Interval and Region3
  include/ignition/math/Interval.hh
  include/ignition/math/Region3.hh
Labels: 🌱 garden, MBARI-LRAUV
