Repository gazebosim/gz-math, pull requests merged in 2023-10, with the labels that each got.

#561 Fix Matrix3_TEST.py on Windows with conda-forge dependencies
  src/python_pybind11/test/Matrix3_TEST.py
Labels: 🌱 garden, 🎵 harmonic

#402 Replace CMake Python variables with new ones from FindPython3 module
  CMakeLists.txt
  src/python_pybind11/CMakeLists.txt
Labels: bug, 🏰 citadel, 🏯 fortress, scripting, Gazebo 1️1️

#553 Remove the use of numeric_limits in appendToStream test
  src/Helpers_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#564 Suppress warnings on MSVC
  include/gz/math/Helpers.hh
Labels: 🏰 citadel, 🏯 fortress
