Repository gazebosim/gz-math, pull requests merged in 2023-08, with the labels that each got.

#543 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden, 🎵 harmonic

#544 Fix documentation on Plane.hh
  include/gz/math/Plane.hh
Labels: beta, 🌱 garden, 🎵 harmonic

#545 Use `pull_request_target` for triage workflow
  .github/workflows/triage.yml
Labels: 🌱 garden, 🎵 harmonic

#547 CI: disable EOL Bionic workflow
  .github/workflows/ci.yml
Labels: 🏰 citadel, beta, 🏯 fortress

#486 MecanumDriveOdometry to handle odometry estimation of Mecanum wheeled models
  include/gz/math/MecanumDriveOdometry.hh
  include/ignition/math/MecanumDriveOdometry.hh
  src/MecanumDriveOdometry.cc
  src/MecanumDriveOdometry_TEST.cc
Labels: enhancement, 🏰 citadel, beta, 🏯 fortress

#546 Fixes for testing in non standard architectures
  src/Helpers_TEST.cc
  src/Pose_TEST.cc
Labels: 🏰 citadel, 🏯 fortress

#550 Merge ign-math6 ➡️ gz-math7
  Changelog.md
  include/gz/math/MecanumDriveOdometry.hh
  include/ignition/math/MecanumDriveOdometry.hh
  src/Helpers_TEST.cc
  src/MecanumDriveOdometry.cc
  src/MecanumDriveOdometry_TEST.cc
  src/Pose_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#552 Prepare for 7.3.0 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden, 🎵 harmonic
