Repository gazebosim/gz-math, pull requests merged in 2024-01, with the labels that each got.

#572 Prepare for 6.15.1 Release
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel, 🏯 fortress

#573 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic

#574 Merge ign-math6 ➡️ gz-math7
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  CMakeLists.txt
  Changelog.md
  src/python_pybind11/CMakeLists.txt
Labels: 🌱 garden, 🎵 harmonic
