Repository gazebosim/gz-math, pull requests merged in 2024-08, with the labels that each got.

#614 Implement rule of zero
  include/gz/math/Color.hh
  include/gz/math/Inertial.hh
  include/gz/math/Line3.hh
  include/gz/math/MassMatrix3.hh
  include/gz/math/Matrix3.hh
  include/gz/math/Matrix4.hh
  include/gz/math/Matrix6.hh
  include/gz/math/OrientedBox.hh
  include/gz/math/Plane.hh
  include/gz/math/Pose3.hh
  include/gz/math/Quaternion.hh
  include/gz/math/SignalStats.hh
  include/gz/math/Vector2.hh
  include/gz/math/Vector3.hh
  include/gz/math/Vector4.hh
  src/SignalStats.cc
  src/SignalStatsPrivate.hh
Labels: beta, 🏛️ ionic

#615 Check for 0 stddev when generating a random number using normal distribution
  src/Rand.cc
  src/Rand_TEST.cc
Labels: beta, 🌱 garden, 🎵 harmonic

#584 Added box examples in cpp and python
  examples/CMakeLists.txt
  examples/box_example.cc
  examples/box_example.py
Labels: beta, 🌱 garden, 🎵 harmonic

#616 Added CoordinateVector3 and used it in SphericalCoordinates
  include/gz/math/Angle.hh
  include/gz/math/CoordinateVector3.hh
  include/gz/math/SphericalCoordinates.hh
  src/Angle.cc
  src/Angle_TEST.cc
  src/CoordinateVector3.cc
  src/CoordinateVector3_TEST.cc
  src/SphericalCoordinates.cc
  src/SphericalCoordinates_TEST.cc
  src/python_pybind11/CMakeLists.txt
  src/python_pybind11/src/Angle.cc
  src/python_pybind11/src/CoordinateVector3.cc
  src/python_pybind11/src/CoordinateVector3.hh
  src/python_pybind11/src/SphericalCoordinates.cc
  src/python_pybind11/src/_gz_math_pybind11.cc
  src/python_pybind11/test/Angle_TEST.py
  src/python_pybind11/test/CoordinateVector3_TEST.py
  src/python_pybind11/test/SphericalCoordinates_TEST.py
  src/ruby/Angle.i
  src/ruby/Angle_TEST.rb
  src/ruby/CMakeLists.txt
  src/ruby/CoordinateVector3.i
  src/ruby/CoordinateVector3_TEST.rb
  src/ruby/SphericalCoordinates.i
  src/ruby/SphericalCoordinates_TEST.rb
  src/ruby/ruby.i
Labels: beta, 🌱 garden, 🏛️ ionic

#619 Update migration guide
  Migration.md
Labels: 🏛️ ionic

#620 Fix tolerance for axis-angle conversion of quaternions
  include/gz/math/Quaternion.hh
  src/Quaternion_TEST.cc
Labels: 🌱 garden, 🎵 harmonic

#618 Ionic Changelog
  Changelog.md
Labels: 🏛️ ionic

#621 Merge gz-math7 ➡️ main
  examples/CMakeLists.txt
  examples/box_example.cc
  examples/box_example.py
  include/gz/math/Quaternion.hh
  src/Quaternion_TEST.cc
  src/Rand.cc
  src/Rand_TEST.cc
Labels: 🏛️ ionic

#623 Prepare for 7.5.1 Release
  CMakeLists.txt
  Changelog.md
  package.xml
Labels: 🌱 garden, 🎵 harmonic

#624 Remove eigen/include/ignition headers
  eigen3/include/CMakeLists.txt
  eigen3/include/ignition/math/eigen3.hh
  eigen3/include/ignition/math/eigen3/Conversions.hh
  eigen3/include/ignition/math/eigen3/Util.hh
Labels: 🏛️ ionic

#622 README: update main branch references to gz-math8
  README.md
Labels: 🏛️ ionic

#625 Prepare for 8.0.0 prerelease
  CMakeLists.txt
Labels: 🏛️ ionic

#524 buffer_protocol for vectors and matrices in python bindings
  .github/ci/packages.apt
  include/gz/math/Matrix3.hh
  include/gz/math/Matrix4.hh
  include/gz/math/Matrix6.hh
  include/gz/math/Vector2.hh
  include/gz/math/Vector3.hh
  include/gz/math/Vector4.hh
  src/Matrix3_TEST.cc
  src/Matrix4_TEST.cc
  src/Matrix6_TEST.cc
  src/Vector2_TEST.cc
  src/Vector3_TEST.cc
  src/Vector4_TEST.cc
  src/python_pybind11/src/Matrix3.hh
  src/python_pybind11/src/Matrix4.hh
  src/python_pybind11/src/Matrix6.hh
  src/python_pybind11/src/Quaternion.hh
  src/python_pybind11/src/Vector2.hh
  src/python_pybind11/src/Vector3.hh
  src/python_pybind11/src/Vector4.hh
  src/python_pybind11/test/Matrix3_TEST.py
  src/python_pybind11/test/Matrix4_TEST.py
  src/python_pybind11/test/Matrix6_TEST.py
  src/python_pybind11/test/Vector2_TEST.py
  src/python_pybind11/test/Vector3_TEST.py
  src/python_pybind11/test/Vector4_TEST.py
  src/python_pybind11/test/numpy_helpers.py
Labels: beta, Breaking change, 🏛️ ionic
